package com.samadhanx.module.notification.event;

public enum EcosystemEventType {
    CHALLENGE_CREATED,
    CHALLENGE_TRIAGED,
    CHALLENGE_RESOLVED,
    CHALLENGE_ESCALATED_TO_INNOVATION,
    PROPOSAL_SUBMITTED,
    PROPOSAL_STATUS_CHANGED,
    TEAM_CREATED,
    EVALUATION_SUBMITTED,
    PARTNER_MATCHED,
    GRANT_APPROVED,
    PILOT_STARTED,
    PILOT_MILESTONE_REACHED,
    WORK_ITEM_ASSIGNED,
    WORK_ITEM_OVERDUE,
    APPROVAL_REQUESTED,
    APPROVAL_COMPLETED
}
