package com.samadhanx.module.challenge.entity.enums;

public enum ChallengeStatus {
    SUBMITTED,
    AI_PROCESSED,
    ROUTED_TO_DEPARTMENT,
    FLAGGED_DUPLICATE,
    UNDER_DEPARTMENT_TRIAGE,
    DEPARTMENT_IN_PROGRESS,
    RESOLVED_BY_DEPARTMENT,
    INNOVATION_REQUIRED,
    OPEN_FOR_ACADEMIC_PROPOSALS,
    SOLUTION_PROTOTYPING,
    FIELD_PILOT_TESTING,
    MEASURABLE_COMMUNITY_IMPACT,
    REJECTED,
    CLOSED
}
